### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ManShum812** [seanmarpo/webjars-swagger-xss#1]
1

**Comment by seanmarpo** [comment]
Your hosted versions are not returning an `Access-Control-Allow-Origin: *` header in the response. Github pages kindly does this for you automatically, so I use Github to host my payloads.

You can see how this works in: https://github.com/seanmarpo/swagger-xss-payloads

**Comment by ManShum812** [comment]
Hi seanmarpo

Thanks for the response. So  I use Github to host my payloads https://github.com/ManShum812/swagger-xss but it seems like still not working:(

**Comment by seanmarpo** [comment]
I'd follow a guide. Your `CNAME` file is incorrect, and I suspect your repository is misconfigured.

Here's a decent guide to follow: https://dev.to/scc33/how-to-host-a-site-with-a-subdomain-on-github-pages-5a1j
